management:
  endpoint.health.probes.enabled: true
  endpoints.web.exposure.include: health, metrics
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  tracing.enabled: true

otel.sdk.disabled: true

server.port: 8080

spring.application.name: java-backend-sandbox

springdoc:
  api-docs.enabled: true
  swagger-ui.supported-submit-methods: []
